### PR TITLE
fixing https://github.com/artilleryio/minigun-core/issues/1

### PR DESCRIPTION
**Pull request by gajjargaurav**

### CODE REVIEW

**Comment by hassy** [comment]
@gajjargaurav I can't merge this just yet since it doesn't work as discussed: https://github.com/artilleryio/minigun-core/issues/1#issuecomment-126305451

Do you think you will be able to do it soon? If not, I may go ahead and implement it this week - keen to get it into the next release. :)

**Comment by gajjargaurav** [comment]
I've got something lined up until 15th, I can do it after that

**Comment by hassy** [comment]
@gajjargaurav great, thanks! :+1:

**Comment by gajjargaurav** [comment]
@hassy , please check my last commit. That should be helpful

**Comment by hassy** [comment]
Added in https://github.com/shoreditch-ops/minigun-core/pull/8 - closing this.

**Pull request closed without merging**
