### PR TITLE
Update runner.js

### PR DESCRIPTION
**Pull request by christurnbull**
Changed back ticks to single quotes

### CODE REVIEW

**Comment by hassy** [comment]
@christurnbull backticks are needed there for the `${val}` template to work

**Comment by christurnbull** [comment]
Minigun is great and I'm trying to use the library as part of a node project.
Using node v0.12.7 with -harmony flag the backticks cause an error when you require("minigun-core")

Looking into this... I missed the npm warning ("node": ">= 4.2.0") when installing the module.
Node v0.12 doesn't support ES6 string templates. Solution - read the dependency list! 
Thanks

**Comment by hassy** [comment]
@christurnbull If you update the PR to print `val` without using backticks, I'll merge. Why not, if everything else works with 0.12 with --harmony.

**Comment by hassy** [comment]
Closing - will be fixed by changes for https://github.com/shoreditch-ops/minigun/issues/27

**Pull request closed without merging**
